var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/community/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__88f0cc21._.js")
R.c("server/chunks/ssr/agronova_e1f50c0d._.js")
R.c("server/chunks/ssr/agronova_240cbf25._.js")
R.c("server/chunks/ssr/[root-of-the-server]__67f0e71d._.js")
R.c("server/chunks/ssr/45d0c_71680edf._.js")
R.c("server/chunks/ssr/45d0c_next_dist_7248216b._.js")
R.c("server/chunks/ssr/agronova_app_e22f4cdb._.js")
R.c("server/chunks/ssr/45d0c_next_dist_client_components_builtin_global-error_e1654c13.js")
R.c("server/chunks/ssr/[root-of-the-server]__7c464f99._.js")
R.c("server/chunks/ssr/45d0c_next_dist_client_components_e7e9a0cf._.js")
R.c("server/chunks/ssr/45d0c_next_dist_client_components_builtin_forbidden_672b5ea5.js")
R.c("server/chunks/ssr/45d0c_next_dist_client_components_builtin_unauthorized_24c6325c.js")
R.c("server/chunks/ssr/agronova_99dea7b8._.js")
R.c("server/chunks/ssr/agronova__next-internal_server_app_dashboard_community_page_actions_d4f3b283.js")
R.m(69101)
module.exports=R.m(69101).exports
