var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5988e578._.js")
R.c("server/chunks/ssr/agronova_e1f50c0d._.js")
R.c("server/chunks/ssr/agronova_4fa3fff7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__67f0e71d._.js")
R.c("server/chunks/ssr/45d0c_71680edf._.js")
R.c("server/chunks/ssr/45d0c_next_dist_7248216b._.js")
R.c("server/chunks/ssr/agronova_app_e22f4cdb._.js")
R.c("server/chunks/ssr/45d0c_next_dist_client_components_builtin_global-error_e1654c13.js")
R.c("server/chunks/ssr/[root-of-the-server]__7c464f99._.js")
R.c("server/chunks/ssr/45d0c_next_dist_client_components_e7e9a0cf._.js")
R.c("server/chunks/ssr/45d0c_next_dist_client_components_builtin_forbidden_672b5ea5.js")
R.c("server/chunks/ssr/45d0c_next_dist_client_components_builtin_unauthorized_24c6325c.js")
R.c("server/chunks/ssr/agronova_99dea7b8._.js")
R.c("server/chunks/ssr/agronova__next-internal_server_app_dashboard_profile_page_actions_e0eb49cf.js")
R.m(93941)
module.exports=R.m(93941).exports
