// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/community" | "/dashboard/market-price" | "/dashboard/pest-detection" | "/dashboard/profile" | "/dashboard/reports" | "/dashboard/schemes" | "/dashboard/soil-analysis" | "/dashboard/store" | "/dashboard/weather" | "/login" | "/privacy" | "/signup" | "/terms" | "/verify-order"
type AppRouteHandlerRoutes = "/api/analyze-crop" | "/api/analyze-soil" | "/api/analyze-weather-impact" | "/api/auth/otp/send" | "/api/auth/otp/verify" | "/api/community/posts" | "/api/community/posts/[id]" | "/api/community/posts/[id]/comment" | "/api/community/posts/[id]/like" | "/api/community/posts/comment" | "/api/market-price" | "/api/messages" | "/api/messages/[id]" | "/api/news" | "/api/reports/generate" | "/api/store/order/create" | "/api/store/order/verify" | "/api/store/products" | "/api/user/follow" | "/api/user/profile" | "/api/users"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/analyze-crop": {}
  "/api/analyze-soil": {}
  "/api/analyze-weather-impact": {}
  "/api/auth/otp/send": {}
  "/api/auth/otp/verify": {}
  "/api/community/posts": {}
  "/api/community/posts/[id]": { "id": string; }
  "/api/community/posts/[id]/comment": { "id": string; }
  "/api/community/posts/[id]/like": { "id": string; }
  "/api/community/posts/comment": {}
  "/api/market-price": {}
  "/api/messages": {}
  "/api/messages/[id]": { "id": string; }
  "/api/news": {}
  "/api/reports/generate": {}
  "/api/store/order/create": {}
  "/api/store/order/verify": {}
  "/api/store/products": {}
  "/api/user/follow": {}
  "/api/user/profile": {}
  "/api/users": {}
  "/dashboard": {}
  "/dashboard/community": {}
  "/dashboard/market-price": {}
  "/dashboard/pest-detection": {}
  "/dashboard/profile": {}
  "/dashboard/reports": {}
  "/dashboard/schemes": {}
  "/dashboard/soil-analysis": {}
  "/dashboard/store": {}
  "/dashboard/weather": {}
  "/login": {}
  "/privacy": {}
  "/signup": {}
  "/terms": {}
  "/verify-order": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
