// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/dashboard/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/community">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/market-price/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/market-price">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/market-price/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/pest-detection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pest-detection">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/pest-detection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/schemes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/schemes">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/schemes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/soil-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/soil-analysis">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/soil-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/store">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/weather/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/weather">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/weather/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/verify-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-order">> = Specific
  const handler = {} as typeof import("../../../app/verify-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-crop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-crop">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-crop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-soil/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-soil">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-soil/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-weather-impact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-weather-impact">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-weather-impact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/otp/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/otp/send">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/otp/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/otp/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/otp/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/otp/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/community/posts/[id]/comment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts/[id]/comment">> = Specific
  const handler = {} as typeof import("../../../app/api/community/posts/[id]/comment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/community/posts/[id]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts/[id]/like">> = Specific
  const handler = {} as typeof import("../../../app/api/community/posts/[id]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/community/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/community/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/community/posts/comment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts/comment">> = Specific
  const handler = {} as typeof import("../../../app/api/community/posts/comment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/community/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts">> = Specific
  const handler = {} as typeof import("../../../app/api/community/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/market-price/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-price">> = Specific
  const handler = {} as typeof import("../../../app/api/market-price/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../../app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/news">> = Specific
  const handler = {} as typeof import("../../../app/api/news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/generate">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/store/order/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/order/create">> = Specific
  const handler = {} as typeof import("../../../app/api/store/order/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/store/order/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/order/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/store/order/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/store/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/products">> = Specific
  const handler = {} as typeof import("../../../app/api/store/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/follow">> = Specific
  const handler = {} as typeof import("../../../app/api/user/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../../app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
